{% set name = "pymc-extras" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymc_extras-{{ version }}.tar.gz
  sha256: fdd60132e2bb91fcdaa7745b2aa4e07cd5f2fa272eb3524b79f993dcf0bf1123

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pymc >=5.19.1
    - scikit-learn

test:
  imports:
    - pymc_extras
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pymc-devs/pymc-extras
  summary: A home for new additions to PyMC, which may include unusual probability distribitions, advanced model fitting algorithms, or any code that may be inappropriate to include in the pymc repository, but may want to be made available to users.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - fonnesbeck
