schema_version: 1

context:
  name: pymc-extras
  version: 0.12.1
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymc_extras-${{ version }}.tar.gz
  sha256: c128c8217fc956bdc325026f13ba097a48d51c9dab489a7c489e3e04d41a4ebf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - pymc >=6.0,<7.0
    - arviz >=1.1
    - better-optimize >=0.4.2,<1.0
    - pydantic >=2.0.0
    - preliz >=0.26.0,<0.27.0
tests:
  - python:
      imports:
        - pymc_extras
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  summary: A home for new additions to PyMC, which may include unusual probability distribitions, advanced model fitting algorithms, or any code that may be inappropriate to include in the pymc repository, but may want to be made available to users.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/pymc-devs/pymc-extras

extra:
  recipe-maintainers:
    - jessegrabowski
    - ricardoV94
    - maresb
    - fonnesbeck
