schema_version: 1

context:
  name: pymc-extras
  version: 0.14.0
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymc_extras-${{ version }}.tar.gz
  sha256: db1f720feba71a8aa61aa083d018526da414f00db183f14694d6e0e3d0a62d5e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - pymc >=6.2.0,<6.3
    - arviz >=1.2,<2.0
    - better-optimize >=0.4.2,<1.0
    - pydantic >=2.0.0,<3.0
    - preliz >=0.27.0,<0.28.0
    - pytensor >=3.2.3,<3.3
tests:
  - python:
      imports:
        - pymc_extras
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  summary: A home for new additions to PyMC, which may include unusual probability distribitions, advanced model fitting algorithms, or any code that may be inappropriate to include in the pymc repository, but may want to be made available to users.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/pymc-devs/pymc-extras

extra:
  recipe-maintainers:
    - jessegrabowski
    - ricardoV94
    - maresb
    - fonnesbeck
